In [12]:
# 1. 필요한 라이브러리 설치
%pip install requests beautifulsoup4 pandas surya-ocr google-genai cloudscraper

Requirement already satisfied: requests in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (4.14.3)
Requirement already satisfied: pandas in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: surya-ocr in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (0.17.0)
Requirement already satisfied: google-genai in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (1.60.0)
Collecting cloudscraper
  Downloading cloudscraper-1.2.71-py2.py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from requests) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>=1.6.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.22.4 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: click<9.0.0,>=8.1.8 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (8.3.1)
Requirement already satisfied: einops<0.9.0,>=0.8.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (0.8.1)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (1.2.0)
Requirement already satisfied: opencv-python-headless==4.11.0.86 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (4.11.0.86)
Requirement already satisfied: pillow<11.0.0,>=10.2.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (10.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.3.6 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (4.5.1)
Requirement already satisfied: pre-commit<5.0.0,>=4.2.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (4.5.1)
Requirement already satisfied: pydantic<3.0.0,>=2.5.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (2.12.5)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.1.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (2.12.0)
Requirement already satisfied: pypdfium2==4.30.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (4.30.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (1.2.1)
Requirement already satisfied: torch<3.0.0,>=2.7.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (2.9.0)
Requirement already satisfied: transformers>=4.56.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from surya-ocr) (4.57.3)
Requirement already satisfied: cfgv>=2.0.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (3.5.0)
Requirement already satisfied: identify>=1.0.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (2.6.16)
Requirement already satisfied: nodeenv>=0.11.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (1.10.0)
Requirement already satisfied: pyyaml>=5.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (6.0.3)
Requirement already satisfied: virtualenv>=20.10.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (20.36.1)
Requirement already satisfied: annotated-types>=0.6.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (0.4.2)
Requirement already satisfied: filelock in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.20.1)
Requirement already satisfied: sympy>=1.13.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.4.2)
Requirement already satisfied: jinja2 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.5.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-genai) (4.12.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai) (2.48.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-genai) (0.28.1)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-genai) (9.1.2)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-genai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-genai) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (1.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (46.0.3)
Requirement already satisfied: rsa<5,>=3.1.4 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (4.9.1)
Requirement already satisfied: httpcore==1.* in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: pyasn1>=0.1.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.6.2)
Requirement already satisfied: pyparsing>=2.4.7 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from cloudscraper) (3.2.5)
Collecting requests-toolbelt>=0.9.1 (from cloudscraper)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: cffi>=2.0.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (2.0.0)
Requirement already satisfied: pycparser in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (2.23)
Requirement already satisfied: six>=1.5 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from sympy>=1.13.3->torch<3.0.0,>=2.7.0->surya-ocr) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from transformers>=4.56.1->surya-ocr) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from transformers>=4.56.1->surya-ocr) (25.0)
Requirement already satisfied: regex!=2019.12.17 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from transformers>=4.56.1->surya-ocr) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from transformers>=4.56.1->surya-ocr) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from transformers>=4.56.1->surya-ocr) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from transformers>=4.56.1->surya-ocr) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=4.56.1->surya-ocr) (1.2.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit<5.0.0,>=4.2.0->surya-ocr) (0.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages (from jinja2->torch<3.0.0,>=2.7.0->surya-ocr) (3.0.3)
Downloading cloudscraper-1.2.71-py2.py3-none-any.whl (99 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Installing collected packages: requests-toolbelt, cloudscraper
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [cloudscraper]
Successfully installed cloudscraper-1.2.71 requests-toolbelt-1.0.0
Note: you may need to restart the kernel to use updated packages.

# 인디스워크 채용 공고 크롤러 (최종 완성판)
- 공고 목록 자동 수집 (페이지 넘김 지원)
- **데이터 분리 저장**:
  1. `content_text`: 순수 본문 텍스트 (지원 버튼 문구 제거됨)
  2. `content_images`: 본문 내 이미지 URL들
  3. `apply_url`: '지원하러 가기' 버튼의 실제 링크
- 결과 CSV 파일로 저장

In [24]:
import cloudscraper
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import os

# -----------------------------------------------------
# 설정
# -----------------------------------------------------
TARGET_PAGES = 4

scraper = cloudscraper.create_scraper()

def get_headers(referer="https://inthiswork.com/"):
    """
    맥(Mac) 크롬 브라우저와 최대한 비슷하게 헤더를 구성합니다.
    """
    return {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
        'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
        'Referer': referer,
        'DNT': '1',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'same-origin',
        'Sec-Fetch-User': '?1'
    }

def get_job_list(pages=3):
    print("=== 공고 목록 수집 시작 ===")
    all_jobs = []
    
    # 세션을 사용하면 쿠키가 유지되어 더 사람처럼 인식될 가능성이 높습니다.
    session = requests.Session()
    for page in range(1, pages + 1):
        url = "https://inthiswork.com/it" if page == 1 else f"https://inthiswork.com/it?paged1={page}"
        referer = "https://inthiswork.com/" if page == 1 else "https://inthiswork.com/it"
            
        time.sleep(random.uniform(2, 4))
        print(f"[{page}페이지] 목록 수집 중... ({url})")
        
        try:
            resp = scraper.get(url, headers=get_headers(referer), timeout=20)
            
            # 차단 여부 확인용 로그
            if resp.status_code != 200:
                print(f"  → 에러: 접속 실패 (상태 코드 {resp.status_code})")
                continue
                
            soup = BeautifulSoup(resp.text, 'html.parser')
            
            # 핵심 변경: 컨테이너에 국한되지 않고 페이지 전체에서 공고 항목 직접 탐색
            entries = soup.select('.dpt-entry')
            
            if not entries:
                # 만약 항목을 못 찾았다면, 다른 클래스명으로 다시 시도
                entries = soup.select('.dpt-entry-wrapper')
            
            print(f"  → {len(entries)}개 공고 발견")
            for entry in entries:
                # 링크와 제목이 포함된 태그 찾기
                link_obj = entry.select_one('a.dpt-title-link') or entry.select_one('.dpt-title a')
                
                if link_obj and link_obj.get('href'):
                    full_url = link_obj.get('href')
                    full_text = link_obj.get_text(strip=True)
                    
                    if '/archives/' not in full_url: 
                        continue
                    # 제목 구분자 처리 (공백 및 특수문자 대응)
                    if '｜' in full_text:
                        parts = full_text.split('｜', 1)
                    elif '|' in full_text:
                        parts = full_text.split('|', 1)
                    else:
                        parts = ["-", full_text]
                    
                    company = parts[0].strip() if len(parts) > 1 else "-"
                    title = parts[1].strip() if len(parts) > 1 else parts[0].strip()

                    # 회사명이 없거나(-) 혹은 "IN THIS WORK"를 포함하는 경우(인터뷰/콘텐츠) 제외
                    if company == "-" or "IN THIS WORK" in company.upper():
                        print(f"  → 제외: {company} | {title}") # 제외되는 공고 로그 출력 (선택 사항)
                        continue
                    
                    # 중복 체크
                    if not any(j['url'] == full_url for j in all_jobs):
                        all_jobs.append({
                            'company': company,
                            'title': title,
                            'url': full_url
                        })
                        
        except Exception as e:
            print(f"  → 에러 발생: {e}")
    return all_jobs

def get_job_detail(url):
    """
    상세 정보 추출 (텍스트, 이미지, 지원링크 분리)
    """
    time.sleep(random.uniform(4, 8))
    try:
        resp = scraper.get(url, headers=get_headers("https://inthiswork.com/it"), timeout=20)

        if resp.status_code != 200:
            print(f"  → 접속 거부됨 ({resp.status_code}): {url}")
            return "", "", ""


        soup = BeautifulSoup(resp.text, 'html.parser')
        
        content_area = (
            soup.select_one('.fusion-content-tb') or 
            soup.select_one('.fusion-content-tb-1') or 
            soup.select_one('.fusion-content-tb-2') or 
            soup.select_one('.post-content') or 
            soup.select_one('.entry-content')
        )
        
        # 영역 찾기 실패 시 디버깅을 위해 HTML 길이를 출력해봅니다.
        if not content_area:
            print(f"  → 내용 영역 미발견 (HTML 길이: {len(resp.text)}): {url}")
            # 만약 보안 페이지가 아니라면, 최소한의 텍스트라도 가져오기 위해 body 전체를 설정
            if len(resp.text) > 2000: # 정상적인 페이지로 보일 때
                content_area = soup.find('body')
            else:
                return "", "", ""
        
        # 1. 지원하기 버튼 링크 추출 (.maxbutton 또는 텍스트로 찾기)
        apply_link_obj = content_area.select_one('a.maxbutton')
        if not apply_link_obj:
            # 클래스가 없을 경우 텍스트로 찾기
            for a in content_area.select('a'):
                if "지원하러" in a.get_text() or "지원하기" in a.get_text():
                    apply_link_obj = a
                    break
        
        apply_url = ""
        if apply_link_obj:
            apply_url = apply_link_obj.get('href', '')
            # 본문 텍스트에서 '지원하러 가기' 문구를 없애기 위해 태그 삭제
            apply_link_obj.decompose()

        # 2. 이미지 추출 (decompose 전에 해야 함, 하지만 버튼은 이미지와 상관없으므로 순서 무관)
        images = content_area.select('img')
        image_links = [img.get('src') for img in images if img.get('src')]
        images_str = ", ".join(image_links)

        # 3. 텍스트 추출 (버튼 태그가 삭제된 상태에서 추출)
        text_content = content_area.get_text(separator='\n', strip=True)
        
        return text_content[:5000], images_str, apply_url

    except Exception as e:
        print(f"  → 상세 에러({url}): {e}")
        return "", "", ""

# --- 실행 ---
job_list = get_job_list(pages=TARGET_PAGES)

full_data = []
if job_list:
    print("\n=== 상세 정보 수집 시작 ===")
    for idx, job in enumerate(job_list):
        print(f"[{idx+1}/{len(job_list)}] {job['title'][:15]}...")
        
        # 3가지 정보 받아오기
        text, imgs, apply_url = get_job_detail(job['url'])
        
        job['content_text'] = text
        job['content_images'] = imgs
        job['apply_url'] = apply_url
        
        full_data.append(job)

    # 저장
    df = pd.DataFrame(full_data)
    save_file = "recruitment_results_full.csv"

    if os.path.exists(save_file):
        # 파일이 있으면: 헤더 없이(header=False), 추가 모드(mode='a')로 저장
        df.to_csv(save_file, mode='a', header=False, index=False, encoding='utf-8-sig')
        print(f"\n[추가 완료] 기존 파일 뒤에 {len(df)}건이 추가되었습니다.")
    else:
        # 파일이 없으면: 헤더 포함(header=True), 쓰기 모드(mode='w')로 신규 생성
        df.to_csv(save_file, mode='w', header=True, index=False, encoding='utf-8-sig')
        print(f"\n[저장 완료] 새 파일에 {len(df)}건이 저장되었습니다.")
    
    # 결과 확인 (apply_url 컬럼 추가됨)
    pd.set_option('display.max_columns', None)
    
    # 현재 수집된 데이터만 확인
    display(df[['company', 'title', 'apply_url']].head())

=== 공고 목록 수집 시작 ===
[1페이지] 목록 수집 중... (https://inthiswork.com/it)
  → 44개 공고 발견
  → 제외: - | 2026 상반기 S-개발자 4기 모집
  → 제외: IN THIS WORK 인터뷰 | 한국딥러닝 채용
  → 제외: - | 스타트업 vs 대기업, 경험자들이 알려주는 스타트업과 대기업의 차이!ㅣ코딥토크쇼
  → 제외: - | 신입 개발자 채용 공고 분석해 드립니다
  → 제외: - | 신입 개발자 채용 트렌드 총정리.zip
  → 제외: - | 개발자 이력서, 제발 이렇게 쓰지 마세요!
[2페이지] 목록 수집 중... (https://inthiswork.com/it?paged1=2)
  → 44개 공고 발견
  → 제외: - | 2026년 상반기 현대케피코 신입채용(채용연계형 인턴)
  → 제외: - | 2026년 상반기 DY그룹 신입/경력 채용
[3페이지] 목록 수집 중... (https://inthiswork.com/it?paged1=3)
  → 44개 공고 발견
  → 제외: - | 환인제약(주) 상시 인재pool 등록
  → 제외: - | 소상공인 힘보탬 박람회 대학생 아이디어 경진대회
[4페이지] 목록 수집 중... (https://inthiswork.com/it?paged1=4)
  → 44개 공고 발견
  → 제외: - | 2026년 상반기 코오롱베니트 채용연계형 인턴 모집

=== 상세 정보 수집 시작 ===
[1/130] Security Resear...
[2/130] 2026년 상반기 신입/경력...
[3/130] [신입/경력] 백엔드 엔지니...
[4/130] AI Software Eng...
[5/130] Robotics S/W En...
[6/130] 3D Computer Vis...
[7/130] [연구소] 네트워크보안솔루션...
[8/130] [연구소] AI솔루션 개발자...
[9/130] Product Enginee...
[10/130] 대외 SI/SM 사업 프로젝...
[11/130] Backend 개발자 (경력...
[12/130] AI 연구원 (경력)...
[13/130] 클라우드 엔지니어 (경력)...
[14/130] SaaS 엔지니어 (경력)...
[15/130] ML Research Sci...
[16/130] [경력무관] Wallet S...
[17/130] 정보보호 (모의해킹/취약점진...
[18/130] 2026년 직원 채용(1차)...
[19/130] 2026년 대규모 개발 채용...
[20/130] 2026년도 상반기 신입직원...
[21/130] Internal Agent ...
[22/130] 네트워크 검증 담당 채용...
[23/130] 대학생 체험형 인턴사원 공개...
[24/130] Sales Engineer ...
[25/130] SAP RAP(Restful...
[26/130] 2026년 신입사원 채용...
[27/130] [기획조정본부] 플랫폼개발팀...
[28/130] [기획조정본부] 정보전략팀 ...
[29/130] [PCC 개발센터] 설계 자...
[30/130] Information Sec...
[31/130] Technical Staff...
[32/130] Data Center Tec...
[33/130] Perception Trac...
[34/130] AI Fusion Engin...
[35/130] Machine Learnin...
[36/130] AI Engineer 채용...
[37/130] 최강자전 – 2주 실전 개발...
[38/130] 【체험형 인턴】 소프트웨어 ...
[39/130] 시스템운영실 웹퍼블리셔 모집...
[40/130] 기술개발연구실 백엔드 개발자...
[41/130] AI Engineer 모집 ...
[42/130] AI 백엔드 엔지니어...
[43/130] 웹(Web) 백엔드 개발자...
[44/130] 프론트엔드 개발자...
[45/130] IDC 카카오뱅크 죽전 데이...
[46/130] Research Scient...
[47/130] SRE(AWS) 엔지니어 모...
[48/130] [시너지사업사업본부] 경력 ...
[49/130] AI/DT담당 스마트팩토리개...
[50/130] ’26년 1분기 신입/경력 ...
[51/130] [AX Team] Front...
[52/130] IT Intern...
[53/130] Frontend Develo...
[54/130] [로봇개발본부] 로봇응용S/...
[55/130] [로봇개발본부] 로봇응용S/...
[56/130] [텀블벅] 프론트엔드 개발자...
[57/130] [NetsPresso] Ed...
[58/130] AX SEED팀 AI 엔지니...
[59/130] AX-HUB팀 데이터 엔지니...
[60/130] AI Research Eng...
[61/130] 백오피스(관리자사이트) 개발...
[62/130] 전산팀 채용...
[63/130] 2026년 상반기 R&D 상...
[64/130] 2026년 신입 및 경력사원...
[65/130] 2026년 상반기 일반직 직...
[66/130] [플랫폼본부] AI 엔지니어...
[67/130] 2026년 상반기 HMI 엔...
[68/130] Fullstack Devel...
[69/130] [Agentic AI] AI...
[70/130] Front-end Engin...
[71/130] 2026년 1분기 채용...
[72/130] IT Application ...
[73/130] [Assistant] AI연...
[74/130] [Penta Security...
[75/130] [Penta Security...
[76/130] [Penta Security...
[77/130] 2026년 1분기 집중채용 ...
[78/130] 신입 대규모 인재영입...
[79/130] 경력 대규모 인재영입...
[80/130] Application Eng...
[81/130] AI Residency – ...
[82/130] Junior Linux Ke...
[83/130] Software Engine...
[84/130] Software Engine...
[85/130] ML Application ...
[86/130] Compiler DevOps...
[87/130] Quantitative Re...
[88/130] Frontend Develo...
[89/130] Physical AI Eng...
[90/130] [2026 Internshi...
[91/130] Frontend Engine...
[92/130] 2026년 상반기 신입사원(...
[93/130] [HS/ES본부]UNIST ...
[94/130] SW UNIT TEST /V...
[95/130] [채용연계형] Softwar...
[96/130] LLM 서비스 Develop...
[97/130] ML Engineer Int...
[98/130] [공통] 클라우드·인프라 보...
[99/130] [구독] Backend En...
[100/130] [구독] Frontend E...
[101/130] T&T부문 정보보안 컨설팅 ...
[102/130] 전산보안실 KM전산지원팀...
[103/130] [Yanolja NEXT] ...
[104/130] 2026년도 가을학기 KT ...
[105/130] IT개발팀(웹개발자) 신입사...
[106/130] 2026년도 신입직원 채용...
[107/130] [인턴] 글로벌 플랫폼 QA...
[108/130] 상시모집 채용 공고(사무기술...
[109/130] 2026 상반기 GBD CO...
[110/130] AI and Data Spe...
[111/130] [Open to all ex...
[112/130] QA Assistant...
[113/130] AI Researcher &...
[114/130] Customer Succes...
[115/130] [서비스 로봇] 로봇 제어 ...
[116/130] [서비스 로봇] 자율주행 로...
[117/130] Software Engine...
[118/130] 정비 전산 시스템 관리 담당...
[119/130] [부산] 인프라 엔지니어 (...
[120/130] 디지털전략부 계약직 채용...
[121/130] 차세대 Cloud API 개...
[122/130] AI Voice Call 서...
[123/130] Cloud Log Analy...
[124/130] 클라우드 보안 솔루션 엔지니...
[125/130] Foundation Mode...
[126/130] Application del...
[127/130] Data Platform M...
[128/130] System Engineer...
[129/130] 음성합성 언어처리 기술 연구...
[130/130] Foundation Mode...

[추가 완료] 기존 파일 뒤에 130건이 추가되었습니다.

,company,title,apply_url
0,토스뱅크,Security Research Specialist,https://toss.im/career/job-detail?job_id=75698...
1,세아제강,2026년 상반기 신입/경력 사원채용,https://seahsteel.recruiter.co.kr/career/job
2,포스타입,[신입/경력] 백엔드 엔지니어,https://about.postype.com/ko/o/199867
3,망고부스트,"AI Software Engineer(Seoul, South Korea)",https://mangoboost.career.greetinghr.com/en/o/...
4,리얼월드(RLWRLD),Robotics S/W Engineer,https://realworld.career.greetinghr.com/ko/o/1...

## 이미지 형식 공고를 OCR로 텍스트로 변환

In [14]:
# --- [2단계] 이미지 OCR 처리 (텍스트 없는 공고 변환) ---
# 사전 설치 필요: %pip install surya-ocr

import requests
import numpy as np
import pandas as pd
from PIL import Image
from io import BytesIO

# == Surya OCR 최신 버전 API 임포트 ==
from surya.detection import DetectionPredictor
from surya.foundation import FoundationPredictor
from surya.recognition import RecognitionPredictor
from surya.common.surya.schema import TaskNames

# 모델 로드 (전역에서 한 번만 수행)
# 처음 실행 시 모델 가중치를 다운로드하므로 시간이 조금 걸릴 수 있습니다.
print("Surya OCR 모델 로딩 중...")
foundation_predictor = FoundationPredictor()
det_predictor = DetectionPredictor()
rec_predictor = RecognitionPredictor(foundation_predictor)
print("모델 로딩 완료.")

def read_text_from_image_url(url):
    """
    URL 이미지를 읽어서 Surya OCR로 텍스트를 반환하는 함수
    """
    try:
        response = requests.get(url, timeout=10)
        if response.status_code != 200: return ""
        
        image_bytes = BytesIO(response.content)
        image = Image.open(image_bytes).convert("RGB")
        
        # 최신 API: Predictor 객체를 직접 호출합니다.
        # 인식할 언어는 자동으로 감지하거나 settings에서 설정됩니다.
        predictions = rec_predictor(
            [image], 
            [TaskNames.ocr_with_boxes], 
            det_predictor=det_predictor
        )
        
        # 결과 텍스트 추출
        if predictions and predictions[0].text_lines:
            full_text = "\n".join([line.text for line in predictions[0].text_lines])
            return full_text
        
        return ""
    except Exception as e:
        print(f"OCR 에러 ({url}): {e}")
        return ""

/data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages/transformers/utils/hub.py:110: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

Surya OCR 모델 로딩 중...

Downloading manifest.json: 100%|██████████| 262/262 [00:00<00:00, 497kB/s]
Downloading specials_dict.json: 100%|██████████| 43.5k/43.5k [00:00<00:00, 46.7MB/s]t_recognition/2025_09_23:   0%|          | 0/12 [00:00<?, ?it/s]
Downloading .gitattributes: 100%|██████████| 1.48k/1.48k [00:00<00:00, 2.05MB/s]
Downloading text_recognition model to /data/ephemeral/home/.cache/datalab/models/text_recognition/2025_09_23:   8%|▊         | 1/12 [00:00<00:07,  1.47it/s]
Downloading processor_config.json: 100%|██████████| 411/411 [00:00<00:00, 1.15MB/s]

Downloading vocab_math.json: 100%|██████████| 20.1k/20.1k [00:00<00:00, 16.9MB/s]

Downloading tokenizer_config.json: 100%|██████████| 694/694 [00:00<00:00, 2.49MB/s]

Downloading README.md: 100%|██████████| 5.05k/5.05k [00:00<00:00, 8.00MB/s]
Downloading text_recognition model to /data/ephemeral/home/.cache/datalab/models/text_recognition/2025_09_23:  17%|█▋        | 2/12 [00:06<00:34,  3.43s/it]
Downloading specials.json: 100%|██████████| 19.6k/19.6k [00:00<00:00, 16.2MB/s]



Downloading config.json: 100%|██████████| 50.2k/50.2k [00:00<00:00, 10.4MB/s]
Downloading special_tokens_map.json: 100%|██████████| 278/278 [00:00<00:00, 223kB/s]

Downloading training_args.bin: 100%|██████████| 7.45k/7.45k [00:00<00:00, 20.8MB/s]
Downloading text_recognition model to /data/ephemeral/home/.cache/datalab/models/text_recognition/2025_09_23:  33%|███▎      | 4/12 [00:06<00:10,  1.32s/it]
Downloading preprocessor_config.json: 100%|██████████| 419/419 [00:00<00:00, 695kB/s]
Downloading model.safetensors: 100%|██████████| 1.34G/1.34G [00:47<00:00, 30.5MB/s]
Downloading text_recognition model to /data/ephemeral/home/.cache/datalab/models/text_recognition/2025_09_23: 100%|██████████| 12/12 [00:48<00:00,  4.05s/it]
Downloading manifest.json: 100%|██████████| 127/127 [00:00<00:00, 210kB/s]
Downloading config.json: 100%|██████████| 858/858 [00:00<00:00, 984kB/s]models/text_detection/2025_05_07:   0%|          | 0/6 [00:00<?, ?it/s]
Downloading README.md: 100%|██████████| 393/393 [00:00<00:00, 414kB/s]
Downloading preprocessor_config.json: 100%|██████████| 373/373 [00:00<00:00, 524kB/s]
Downloading .gitattributes: 100%|██████████| 1.48k/1.48k [00:00<00:00, 10.5MB/s]
Downloading training_args.bin: 100%|██████████| 5.49k/5.49k [00:00<00:00, 11.1MB/s]
Downloading model.safetensors: 100%|██████████| 73.4M/73.4M [00:00<00:00, 274MB/s]
Downloading text_detection model to /data/ephemeral/home/.cache/datalab/models/text_detection/2025_05_07: 100%|██████████| 6/6 [00:06<00:00,  1.01s/it]

모델 로딩 완료.

In [15]:
# 1. CSV 불러오기
df = pd.read_csv("recruitment_results_full.csv")

# 2. '텍스트는 없고(부족하고) 이미지는 있는' 행 찾기
target_mask = (df['content_text'].fillna('').str.len() < 50) & (df['content_images'].notna()) & (df['content_images'] != "")
targets = df[target_mask]
print(f"OCR 변환 대상: 총 {len(targets)}개 공고")

# 3. 순회하며 OCR 수행
for idx, row in targets.iterrows():
    print(f"[{idx}] '{row['title']}' 이미지 분석 중...")
    
    img_urls = str(row['content_images']).split(',')
    ocr_text_all = []
    
    for img_url in img_urls:
        img_url = img_url.strip()
        if not img_url: continue
        
        text = read_text_from_image_url(img_url)
        if text: ocr_text_all.append(text)
            
    if ocr_text_all:
        full_ocr_text = "(이미지 자동 추출 텍스트)\n" + "\n---\n".join(ocr_text_all)
        df.at[idx, 'content_text'] = full_ocr_text
        print("  -> 변환 완료")

# 4. 결과 재저장
df.to_csv("recruitment_results_full_ocr.csv", index=False, encoding='utf-8-sig')
print("\n[완료] 'recruitment_results_full_ocr.csv'가 저장되었습니다.")

OCR 변환 대상: 총 10개 공고
[1] '2026년 상반기 신입/경력 사원채용' 이미지 분석 중...

/data/ephemeral/git/pro-nlp-generationfornlp-nlp-01/.venv/lib/python3.10/site-packages/PIL/Image.py:1056: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Detecting bboxes: 100%|██████████| 1/1 [00:05<00:00,  5.46s/it]
Recognizing Text: 100%|██████████| 321/321 [00:17<00:00, 18.07it/s]

  -> 변환 완료
[9] '대외 SI/SM 사업 프로젝트 관리자(PM) 및 개발자 모집' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:02<00:00,  2.76s/it]
Recognizing Text: 100%|██████████| 62/62 [00:02<00:00, 25.18it/s]

  -> 변환 완료
[16] '정보보호 (모의해킹/취약점진단, 침해사고대응)' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:03<00:00,  3.13s/it]
Recognizing Text: 100%|██████████| 104/104 [00:04<00:00, 25.84it/s]

  -> 변환 완료
[17] '2026년 직원 채용(1차) 공고' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:02<00:00,  2.90s/it]
Recognizing Text: 100%|██████████| 108/108 [00:03<00:00, 32.18it/s]
Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  2.56it/s]
Recognizing Text: 100%|██████████| 55/55 [00:02<00:00, 23.90it/s]
Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
Recognizing Text: 100%|██████████| 97/97 [00:03<00:00, 26.02it/s]
Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
Recognizing Text: 100%|██████████| 66/66 [00:02<00:00, 27.87it/s]
Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  2.47it/s]
Recognizing Text: 100%|██████████| 24/24 [00:01<00:00, 14.49it/s]

  -> 변환 완료
[18] '2026년 대규모 개발 채용' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it]
Recognizing Text: 100%|██████████| 179/179 [00:05<00:00, 34.71it/s]

  -> 변환 완료
[19] '2026년도 상반기 신입직원 채용공고' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.63s/it]
Recognizing Text: 100%|██████████| 183/183 [00:06<00:00, 26.26it/s]

  -> 변환 완료
[22] '네트워크 검증 담당 채용' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s]
Recognizing Text: 100%|██████████| 120/120 [00:03<00:00, 37.39it/s]

  -> 변환 완료
[23] '대학생 체험형 인턴사원 공개채용_AI솔루션부' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
Recognizing Text: 100%|██████████| 63/63 [00:02<00:00, 27.21it/s]

  -> 변환 완료
[25] 'SAP RAP(Restful ABAP) 개발자 모집' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:00<00:00,  3.05it/s]
Recognizing Text: 100%|██████████| 53/53 [00:01<00:00, 28.04it/s]

  -> 변환 완료
[26] '2026년 신입사원 채용' 이미지 분석 중...

Detecting bboxes: 100%|██████████| 1/1 [00:04<00:00,  4.88s/it]
Recognizing Text: 100%|██████████| 425/425 [00:10<00:00, 40.33it/s]

  -> 변환 완료

[완료] 'recruitment_results_full_ocr.csv'가 저장되었습니다.

# 크롤링 후 Json 형식으로 생성하기

## 크롤링 정보를 저장해 놓은 csv 파일에서 데이터 읽어오기

In [20]:
import pandas as pd

# 1. 수집된 CSV 파일 불러오기
# 전처리가 완료된 최종 파일을 불러옵니다.
csv_path = "recruitment_results_full_ocr.csv"

try:
    df = pd.read_csv(csv_path, encoding='utf-8-sig')
    print(f"✅ 파일을 성공적으로 불러왔습니다. (총 {len(df)}개 공고)")
except FileNotFoundError:
    print(f"❌ 파일을 찾을 수 없습니다: {csv_path}")

# 2. 데이터 최종 점검 (결측치 처리)
# 분석 시 에러 방지를 위해 결측치를 빈 문자열이나 기본값으로 채웁니다.
df['content_text'] = df['content_text'].fillna('')
# df['content_images'] = df['content_images'].fillna('')
df['company'] = df['company'].fillna('정보 없음')
df['title'] = df['title'].fillna('제목 없음')

# 3. 대상 지정 (필터링 없이 전체 데이터 사용)
# 이제 특정 조건(이미지 유무 등)에 관계없이 모든 데이터를 분석 대상으로 설정합니다.
df_targets = df.copy() 

print(f"📊 분석 대상 데이터: 총 {len(df_targets)}건 확보 완료")

# 4. 전체 데이터 구조 확인 (상위 5건)
print("\n--- 전체 데이터 샘플 (최상위 5건) ---")
# 필요한 컬럼들만 선택해서 확인
display(df_targets[['company', 'title', 'content_text']].head())

# 이후 단계에서 df_targets를 사용하여 LLM 분석이나 결과 저장을 진행하시면 됩니다.

✅ 파일을 성공적으로 불러왔습니다. (총 40개 공고)
📊 분석 대상 데이터: 총 40건 확보 완료

--- 전체 데이터 샘플 (최상위 5건) ---

,company,title,content_text,content_images
0,토스뱅크,Security Research Specialist,토스뱅크 Affiliation\n계약직\n합류하게 될 팀에 대해 알려드려요\nSec...,
1,세아제강,2026년 상반기 신입/경력 사원채용,(이미지 자동 추출 텍스트)\nSěAH 세아제강\n2026\n세아제강\n신입/경력사...,https://i0.wp.com/inthiswork.com/wp-content/up...
2,포스타입,[신입/경력] 백엔드 엔지니어,취향의 가치를 ​만드는 ​창작 ​커뮤니티\n포스타입에서는 다양한 ​취향을 만족하는 ...,
3,망고부스트,"AI Software Engineer(Seoul, South Korea)",Position Overview\nWe ​are ​looking ​for a ​hi...,
4,리얼월드(RLWRLD),Robotics S/W Engineer,리얼월드\n(RLWRLD)는 로봇이 ​인간처럼 ​세상을 ​인식하고 사고하며 ​행동할...,

## Gemini 설정 및 프롬프트 준비

In [ ]:
from google import genai # import google.genai as genai 대신 이 방식을 권장합니다.
from google.genai import types
import PIL.Image
import requests
from io import BytesIO
import time
import json
import pandas as pd

# 1. 클라이언트(Client) 객체를 생성하며 API 키를 전달합니다.
GOOGLE_API_KEY = ""
client = genai.Client(api_key=GOOGLE_API_KEY)

# 2. 모델명 설정
MODEL_ID = 'gemini-2.5-flash' # 또는 'gemini-2.5-flash' (사용 가능 환경인 경우)
SYSTEM_PROMPT = """채용 공고 전문가로서 다음 지침에 따라 공고 데이터를 분석하여 JSON 리스트로 변환하세요.
1. 한 공고 내에 여러 직무(백엔드, 프론트엔드 등)가 있다면 각각 독립된 JSON 객체로 분리하여 리스트로 만드세요.
2. 표(Table) 형식의 데이터는 행과 열의 관계를 정확히 파악하여 각 직무에 맞게 할당하세요.
3. link에는 실제 지원 페이지로 연결되는 apply_url 정보를 담아주세요.
4. 출력 형식은 반드시 아래 키를 포함하는 JSON 리스트여야 합니다:
   keys: [title, company, link, deadline, location, experience, education, employment_type, salary, job_sector, key_responsibilities, required_qualifications, preferred_qualifications]
"""

## 방식 A: 로컬 OCR (Surya) -> 텍스트 -> Gemini

로컬에서 surya-ocr로 텍스트를 모두 뽑아낸 뒤, 텍스트만 Gemini에게 전달합니다.

In [28]:
def approach_a_ocr_then_gemini(df_row):
    # 1. 기존 텍스트 가져오기
    existing_text = str(df_row['content_text']) if pd.notna(df_row['content_text']) else ""
    
    # 2. 이미지 OCR 수행 (img_urls 추출)
    img_urls = str(df_row['content_images']).split(',') if pd.notna(df_row['content_images']) else []
    ocr_text_all = ""
    
    for url in img_urls:
        url = url.strip()
        if not url: continue
        # 이전에 정의한 Surya OCR 함수 호출
        text = read_text_from_image_url(url) 
        ocr_text_all += f"\n[이미지 추출 텍스트]:\n{text}\n"

    # 3. 통합 텍스트 구성
    combined_input = f"""
    회사명: {df_row['company']}
    공고 제목: {df_row['title']}
    원본 링크: {df_row['url']}
    지원 링크: {df_row['apply_url']}
    
    [본문 텍스트]:
    {existing_text}
    
    {ocr_text_all}
    """

    # 4. Gemini 호출 (신규 SDK 문법)
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=f"다음 데이터를 분석해:\n{combined_input}",
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            response_mime_type="application/json"
        )
    )
    return response.text

## 방식 B : Gemini 멀티모달 (이미지 직접 전달)

Gemini는 이미지 URL을 직접 인식하지 못하므로, 이미지를 다운로드하여 바이트 데이터로 직접 전달

In [29]:
def approach_b_url_direct_gemini(df_row):
    img_urls = str(df_row['content_images']).split(',') if pd.notna(df_row['content_images']) else []
    img_urls_str = "\n".join([f"- {url.strip()}" for url in img_urls if url.strip()])
    existing_text = str(df_row['content_text']) if pd.notna(df_row['content_text']) else ""

    user_prompt = f"""
    다음 채용 공고의 텍스트와 이미지 URL들을 분석하여 정보를 추출하세요.
    
    기본 정보:
    - 회사명: {df_row['company']}
    - 제목: {df_row['title']}
    - 공고 URL: {df_row['url']}
    - 지원 URL: {df_row['apply_url']}
    
    본문 텍스트:
    {existing_text}
    
    분석할 이미지 URL 목록:
    {img_urls_str}
    """

    response = client.models.generate_content(
        model=MODEL_ID,
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            response_mime_type="application/json"
        )
    )
    return response.text

## 비교 실험 실행 코드

In [ ]:
results_comparison = []

def run_gemini_experiment(df_row):
    print(f"\n>>> 분석 중: [{df_row['company']}] {df_row['title']}")
    
    # --- 방식 A: OCR 기반 ---
    try:
        start_a = time.time()
        res_a = approach_a_ocr_then_gemini(df_row)
        time_a = time.time() - start_a
    except Exception as e:
        res_a, time_a = f"Error: {e}", 0

    # --- 방식 B: URL 직접 전달 기반 ---
    try:
        start_b = time.time()
        res_b = approach_b_url_direct_gemini(df_row)
        time_b = time.time() - start_b
    except Exception as e:
        res_b, time_b = f"Error: {e}", 0
    
    results_comparison.append({
        'company': df_row['company'],
        'title': df_row['title'],
        'time_ocr_gemini': time_a,
        'time_url_context': time_b,
        'result_a_len': len(res_a),
        'result_b_len': len(res_b),
        'raw_a': res_a,
        'raw_b': res_b
    })

# 1. 파일 읽기
df = pd.read_csv("recruitment_results_full.csv")

# 2. 테스트용 샘플 추출 (이미지가 있는 데이터 우선)
samples = df[df['content_images'].notna() & (df['content_images'] != "")].head(3)

# 3. 실행
for _, row in samples.iterrows():
    run_gemini_experiment(row)

# 4. 결과 출력
comparison_df = pd.DataFrame(results_comparison)
pd.set_option('display.max_colwidth', 50)
display(comparison_df[['company', 'title', 'time_ocr_gemini', 'time_url_context']])

output_dir = "experiment_results"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
for i, res in enumerate(results_comparison):
    # 회사명과 인덱스로 파일명 생성 (특수문자 제거)
    clean_company = "".join(x for x in res['company'] if x.isalnum())
    
    # 방식 A 결과 저장
    with open(f"{output_dir}/{i}_{clean_company}_approach_A.json", "w", encoding="utf-8") as f:
        f.write(res['raw_a'])
    
    # 방식 B 결과 저장
    with open(f"{output_dir}/{i}_{clean_company}_approach_B.json", "w", encoding="utf-8") as f:
        f.write(res['raw_b'])
print(f"\n📂 상세 JSON 결과가 '{output_dir}' 폴더에 저장되었습니다.")
print("각 파일을 열어서 비교해 보세요!")
# 6. 주피터 노트북에서 바로 내용 일부 확인하기 (첫 번째 샘플)
if results_comparison:
    print("\n--- [직접 확인] 첫 번째 샘플의 방식 B 결과 ---")
    print(results_comparison[0]['raw_b'])

## OCR 완료된 내용들을 json 형식으로 바꾸는 요청

In [ ]:
def analyze_with_gemini(df_row):
    # 1. 가공된 텍스트 가져오기 (이미 OCR 등이 완료된 상태)
    full_text = str(df_row['content_text']) if pd.notna(df_row['content_text']) else ""
    
    # 2. 통합 프롬프트 구성
    combined_input = f"""
    회사명: {df_row['company']}
    공고 제목: {df_row['title']}
    원본 링크: {df_row.get('url', 'N/A')}
    지원 링크: {df_row.get('apply_url', 'N/A')}
    
    [본문 및 OCR 텍스트]:
    {full_text}
    """

    try:
        # 3. Gemini 호출
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=[f"다음 채용 공고를 상세히 분석해서 JSON으로 응답해줘:\n{combined_input}"],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                response_mime_type="application/json"
            )
        )
        
        # JSON 문자열을 파이썬 딕셔너리로 변환
        import json
        result = json.loads(response.text)
        
        # 결과를 담을 리스트 정형화
        # 1. 단일 딕셔너리면 리스트로 감쌈
        # 2. 이미 리스트라면 그대로 사용
        items_to_process = result if isinstance(result, list) else [result]
        
        # 각 결과물에 공통 정보(회사명, 제목 등) 추가
        for item in items_to_process:
            if isinstance(item, dict): # 딕셔너리인 경우만 키 추가
                item['source_company'] = df_row['company']
                item['source_title'] = df_row['title']
                item['source_url'] = df_row.get('url', '')
        
        return items_to_process # 항상 리스트 형태 반환

    except Exception as e:
        print(f"❌ 분석 실패 ({df_row['title']}): {e}")
        return {"error": str(e), "title": df_row['title']}

## 저장하기

In [23]:
import json
from tqdm import tqdm

final_all_results = [] # 모든 공고에서 추출된 모든 JSON 객체가 여기 담깁니다.

print(f"🚀 총 {len(df_targets)}건 분석 시작...")

for index, row in tqdm(df_targets.iterrows(), total=len(df_targets)):
    # 결과가 리스트로 옵니다 (예: [{}, {}] 또는 [{}])
    batch_results = analyze_with_gemini(row)
    
    # extend를 사용하여 합칩니다.
    final_all_results.extend(batch_results)

# 3. 저장
output_filename = "final_recruitment_all_items.json"
with open(output_filename, "w", encoding="utf-8") as f:
    json.dump(final_all_results, f, ensure_ascii=False, indent=4)

print(f"✅ 총 {len(final_all_results)}개의 데이터가 '{output_filename}'에 저장되었습니다.")

🚀 총 40건 분석 시작...

 22%|██▎       | 9/40 [01:55<03:41,  7.16s/it]

❌ 분석 실패 (Product Engineer (Full-Stack)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 34.458896721s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}

 25%|██▌       | 10/40 [01:56<02:31,  5.04s/it]

❌ 분석 실패 (대외 SI/SM 사업 프로젝트 관리자(PM) 및 개발자 모집): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 34.168909404s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}

 28%|██▊       | 11/40 [01:56<01:43,  3.58s/it]

❌ 분석 실패 (Backend 개발자 (경력)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 33.875968935s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '33s'}]}}

 30%|███       | 12/40 [01:56<01:12,  2.58s/it]

❌ 분석 실패 (AI 연구원 (경력)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 33.584650271s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '33s'}]}}

 32%|███▎      | 13/40 [01:57<00:50,  1.89s/it]

❌ 분석 실패 (클라우드 엔지니어 (경력)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 33.293988756s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '33s'}]}}

 35%|███▌      | 14/40 [01:57<00:36,  1.40s/it]

❌ 분석 실패 (SaaS 엔지니어 (경력)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 33.006240934s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '33s'}]}}

 38%|███▊      | 15/40 [01:57<00:26,  1.07s/it]

❌ 분석 실패 (ML Research Scientist): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 32.719363941s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}

 40%|████      | 16/40 [01:57<00:20,  1.18it/s]

❌ 분석 실패 ([경력무관] Wallet Security Engineer (블록체인)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 32.394995281s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}

 42%|████▎     | 17/40 [01:58<00:15,  1.47it/s]

❌ 분석 실패 (정보보호 (모의해킹/취약점진단, 침해사고대응)): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 32.103584094s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}

 45%|████▌     | 18/40 [01:58<00:12,  1.72it/s]

❌ 분석 실패 (2026년 직원 채용(1차) 공고): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 31.748458655s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '31s'}]}}

 48%|████▊     | 19/40 [01:58<00:10,  1.99it/s]

❌ 분석 실패 (2026년 대규모 개발 채용): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 31.431718487s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '31s'}]}}

 50%|█████     | 20/40 [01:59<00:08,  2.29it/s]

❌ 분석 실패 (2026년도 상반기 신입직원 채용공고): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 31.131596801s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '31s'}]}}

 52%|█████▎    | 21/40 [01:59<00:07,  2.55it/s]

❌ 분석 실패 (2026 상반기 S-개발자 4기 모집): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 30.851372796s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '30s'}]}}

 55%|█████▌    | 22/40 [01:59<00:06,  2.74it/s]

❌ 분석 실패 (Internal Agent Builder 인턴): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 30.56125417s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '30s'}]}}

 57%|█████▊    | 23/40 [02:00<00:05,  2.90it/s]

❌ 분석 실패 (네트워크 검증 담당 채용): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 30.260718764s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '30s'}]}}

 60%|██████    | 24/40 [02:00<00:05,  3.03it/s]

❌ 분석 실패 (대학생 체험형 인턴사원 공개채용_AI솔루션부): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 29.965952154s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '29s'}]}}

 85%|████████▌ | 34/40 [04:21<00:54,  9.07s/it]

❌ 분석 실패 (한국딥러닝 채용): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 9.253285092s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '9s'}]}}

 88%|████████▊ | 35/40 [04:21<00:32,  6.43s/it]

❌ 분석 실패 (스타트업 vs 대기업, 경험자들이 알려주는 스타트업과 대기업의 차이!ㅣ코딥토크쇼): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 8.965400127s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '8s'}]}}

 90%|█████████ | 36/40 [04:21<00:18,  4.59s/it]

❌ 분석 실패 (신입 개발자 채용 공고 분석해 드립니다): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 8.681332754s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '8s'}]}}

 92%|█████████▎| 37/40 [04:21<00:09,  3.29s/it]

❌ 분석 실패 (신입 개발자 채용 트렌드 총정리.zip): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 8.402916681s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '8s'}]}}

 98%|█████████▊| 39/40 [04:39<00:05,  5.31s/it]

❌ 분석 실패 (Perception Tracking Engineer): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 50.911158448s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}

100%|██████████| 40/40 [04:39<00:00,  6.99s/it]

❌ 분석 실패 (AI Fusion Engineer): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 50.622315075s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
✅ 총 103개의 데이터가 'final_recruitment_all_items.json'에 저장되었습니다.